// Get
export const FETCH_WEATHER_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_WEATHER_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_WEATHER_FAILURE = "FETCH_USERS_FAILURE";

export const FETCH_CITY_REQUEST = "FETCH_CITY_REQUEST";
export const FETCH_CITY_SUCCESS = "FETCH_CITY_SUCCESS";
export const FETCH_CITY_FAILURE = "FETCH_CITY_FAILURE";

export const FETCH_WEEEKLY_REQUEST = "FETCH_WEEEKLY_REQUEST";
export const FETCH_WEEKLY_SUCCESS = "FETCH_WEEKLY_SUCCESS";
export const FETCH_WEEKLY_FAILURE = "FETCH_WEEKLY_FAILURE";

export const UPDATE_CURRENT_LOCATION = "UPDATE_CURRENT_LOCATION";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
